#!/bin/bash

TYPE=$(cat TYPE)

if [[ -z "${TYPE}" ]]
then 	
    echo "Please use the correct type of work"
    exit 1
fi

mkdir -p ${TYPE}
cp -R template/phdthesr-skel/"${TYPE}"/* "${TYPE}"

for i in thesis synopsis
do
    if [[ -d "${TYPE}"/"${i}" ]]
    then	
	cp -R template/kermit-makefiles/makefiles/* "${TYPE}"/"${i}"
	cp -R template/kermit-makefiles/scripts/bibtool/biblatex/* "${TYPE}"/"${i}"/bib
	cp -R template/phdthesr/* "${TYPE}"/"${i}"
	cp -R template/common-template/"${i}"/* "${TYPE}"/"${i}"
    fi
done
cp -R template/phdthesr-template/"${TYPE}"/* "${TYPE}"

